TEAMMANAGE-516: Updated git pre-commit hook

diff --git a/tools/githooks/pre-commit b/tools/githooks/pre-commit
--- a/tools/githooks/pre-commit
+++ b/tools/githooks/pre-commit
@@ -19,28 +19,21 @@ if [ "$old_stash" = "$new_stash" ]; then
     exit 0
 fi
 
-DIR=$(php -r "echo dirname(dirname(dirname(realpath('$0'))));")
-STAGED_FILES=$(git diff-index --name-only --cached --diff-filter=ACMR HEAD | grep '\.md$')
-
 status=0
 
-if [ "$STAGED_FILES" != "" ]; then
-		FILES=""
-		for file in $STAGED_FILES; do
-			FILES="$FILES $file"
-		done
+DIR=$(php -r "echo dirname(dirname(dirname(realpath('$0'))));")
+STAGED_FILES=$(git diff-index --name-only --cached --diff-filter=ACMR HEAD | grep '\.md$' | tr '\n' ' ')
 
-		echo "Running Markdown linter..."
-		echo ""
-		$DIR/tools/node_modules/.bin/markdownlint --config=$DIR/tools/.markdownlint.json $FILES
-		if [ $? != 0 ]
-		then
-				(>&2 echo)
-				(>&2 echo)
-				(>&2 echo "Fix the errors before commit.")
-				(>&2 echo)
-				status=1
-				fi
+if [ "$STAGED_FILES" != "" ]; then
+  echo "Running Markdown linter..."
+  $DIR/tools/node_modules/.bin/markdownlint --config=$DIR/tools/.markdownlint.json $STAGED_FILES
+  status=$?
+  if [ $status != 0 ]; then
+    (>&2 echo)
+    (>&2 echo)
+    (>&2 echo "Fix the errors before commit.")
+  (>&2 echo)
+  fi
 fi
 
 # Restore changes
